2025-05-24 17:54:10,513 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.6.1.152:43983'
2025-05-24 17:54:11,560 - distributed.worker - INFO -       Start worker at:     tcp://10.6.1.152:46097
2025-05-24 17:54:11,560 - distributed.worker - INFO -          Listening to:     tcp://10.6.1.152:46097
2025-05-24 17:54:11,560 - distributed.worker - INFO -           Worker name:             SLURMCluster-6
2025-05-24 17:54:11,560 - distributed.worker - INFO -          dashboard at:           10.6.1.152:45897
2025-05-24 17:54:11,560 - distributed.worker - INFO - Waiting to connect to: tcp://146.186.150.11:35323
2025-05-24 17:54:11,560 - distributed.worker - INFO - -------------------------------------------------
2025-05-24 17:54:11,560 - distributed.worker - INFO -               Threads:                          1
2025-05-24 17:54:11,560 - distributed.worker - INFO -                Memory:                 100.00 GiB
2025-05-24 17:54:11,560 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-9vwqlo73
2025-05-24 17:54:11,561 - distributed.worker - INFO - -------------------------------------------------
2025-05-24 17:54:11,618 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-05-24 17:54:11,619 - distributed.worker - INFO -         Registered to: tcp://146.186.150.11:35323
2025-05-24 17:54:11,619 - distributed.worker - INFO - -------------------------------------------------
2025-05-24 17:54:11,619 - distributed.core - INFO - Starting established connection to tcp://146.186.150.11:35323
2025-05-24 18:29:07,113 - distributed.worker - ERROR - Compute Failed
Key:       model_climatology-b123ac4b-922e-4c2f-9a8a-d60b4015009e
State:     executing
Task:  <Task 'model_climatology-b123ac4b-922e-4c2f-9a8a-d60b4015009e' model_climatology(...)>
Exception: 'AttributeError("\'DataArray\' object has no attribute \'wind_speed\'")'
Traceback: '  File "/tmp/ipykernel_2988808/3492169445.py", line 30, in model_climatology\n  File "/storage/work/cta5244/.conda/envs/fwi_env/lib/python3.10/site-packages/xarray/core/common.py", line 306, in __getattr__\n    raise AttributeError(\n'

slurmstepd: error: *** JOB 38705089 ON p-sc-2382 CANCELLED AT 2025-05-24T18:54:19 DUE TO TIME LIMIT ***
